//USERS
export const GOOGLE_SIGIN = 'GOOGLE_SIGIN'
export const FB_SIGNIN = 'FB_SIGNIN'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const UPDATE_BORROW_COUNT= 'UPDATE_BORROW_COUNT'
export const UPDATE_RETURN_COUNT= 'UPDATE_RETURN_COUNT'